import { Injector, EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { ColumnMode, SelectionType, SortType, DatatableComponent } from '@swimlane/ngx-datatable';
import { DatatableColumn, Page, DatatableFilter, Keyword } from '@xaphira/ngxa-common';
import { LayoutService } from '@xaphira/ngxa-theme';
import { HttpFactoryService, HttpBaseModel } from '@xaphira/shared';
import { FormGroup } from '@angular/forms';
export declare class NgxaCerDatatableComponent implements OnInit, OnDestroy {
    locale: string;
    private layout;
    injector: Injector;
    rows: any[];
    columns: DatatableColumn[];
    filters: DatatableFilter[];
    selected: any[];
    limit: number | undefined;
    count: number;
    offset: number;
    externalPaging: boolean;
    externalSorting: boolean;
    loadingIndicator: boolean;
    scrollbarH: boolean;
    scrollbarV: boolean;
    reorderable: boolean;
    sortType: SortType;
    messages: any;
    selectionType: SelectionType;
    columnMode: ColumnMode;
    headerHeight: any;
    footerHeight: any;
    rowHeight: number | 'auto' | ((row?: any) => number);
    column: boolean;
    footer: boolean;
    api: HttpBaseModel;
    startWithOpenData: boolean;
    filterEvent: boolean;
    formGroupFilter: FormGroup;
    buttonCell: EventEmitter<any>;
    select: EventEmitter<any>;
    activate: EventEmitter<any>;
    datatable: DatatableComponent;
    filterFn: Keyword;
    keywordParam: Keyword;
    _keyword: Keyword;
    protected http: HttpFactoryService;
    private destroy$;
    private cdref;
    private sort;
    private pageOffset;
    constructor(locale: string, layout: LayoutService, injector: Injector);
    ngOnInit(): void;
    ngOnDestroy(): void;
    fetch(): void;
    onSort(order: any): void;
    onSelect(selected: any): void;
    onActivate(event: any): void;
    setPage(page: Page): void;
    sanitizedValue(value: any): any;
    stripHtml(html: string): string;
    onClickButton(event: any): void;
    private getRequest;
}
