import { OnInit, OnDestroy, Injector } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { NbDialogService } from '@nebular/theme';
import { BaseFilterComponent, DatatableColumn, Sort, SelectParamModel } from '@xaphira/ngxa-common';
import { PanicFactoryService, HttpBaseModel } from '@xaphira/shared';
export declare class NgxaCerMonitoringDetailComponent extends BaseFilterComponent<any> implements OnInit, OnDestroy {
    injector: Injector;
    private router;
    private route;
    private panicService;
    private dialogService;
    profile: any;
    image: string;
    imageDefault: string;
    apiPath: HttpBaseModel;
    columns: DatatableColumn[];
    sort: Sort;
    apiSelectParameter: HttpBaseModel;
    paramSelectStatus: SelectParamModel[];
    paramSelectEmergency: SelectParamModel[];
    disabledFake: boolean;
    private panicCode;
    private username;
    private oauthResource;
    private enc;
    constructor(injector: Injector, router: Router, route: ActivatedRoute, panicService: PanicFactoryService, dialogService: NbDialogService);
    ngOnDestroy(): void;
    ngOnInit(): void;
    onInit(serviceName: string, apiName: string): void;
    valueSelect(prop: string): string;
    onPreview(data: any): void;
    onFake(): void;
    onProcess(): void;
}
