import { OnInit, Injector, OnDestroy } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { HttpBaseModel, IndexedDBFactoryService } from '@xaphira/shared';
import { UserInfo } from '@xaphira/shared';
import { BaseFormComponent, SelectParamModel } from '@xaphira/ngxa-common';
export declare class ProfilePageComponent extends BaseFormComponent<any> implements OnInit, OnDestroy {
    injector: Injector;
    private userService;
    private profileIndexedDB;
    image: string;
    formGroupImage: FormGroup;
    uploadFinished: boolean;
    patternEmail: string;
    patternPhoneNumber: string;
    minLength: number;
    disabledUpload: boolean;
    apiSelectCountry: HttpBaseModel;
    apiSelectProvince: HttpBaseModel;
    paramSelectProvince: SelectParamModel[];
    apiSelectCity: HttpBaseModel;
    paramSelectCity: SelectParamModel[];
    apiSelectDistrict: HttpBaseModel;
    paramSelectDistrict: SelectParamModel[];
    apiSelectSubDistrict: HttpBaseModel;
    paramSelectSubDistrict: SelectParamModel[];
    constructor(injector: Injector, userService: UserInfo, profileIndexedDB: IndexedDBFactoryService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    onInit(serviceName: string, apiName: string): void;
    onSelectCountry(select: any): void;
    onSelectProvince(select: any): void;
    onSelectCity(select: any): void;
    onSelectDistrict(select: any): void;
    onClearCountry(): void;
    onClearProvince(): void;
    onClearCity(): void;
    onClearDistrict(): void;
    uploadImage(file: any): void;
    valueSelect(prop: string): string;
    onSubmit(): void;
}
